version: '3.8'

services:
  babapp-front:
    restart: always
    networks:
      - traefik-public
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.babapp-front.tls=true"
      - "traefik.http.routers.babapp-front.tls.certresolver=le"
      - "traefik.http.routers.babapp-front.entrypoints=websecure"
      - "traefik.http.routers.babapp-front.service=babapp-front"
      - "traefik.http.routers.babapp-front.rule=Host(`panel.dashaljawhara.com`)"
      - "traefik.http.services.babapp-front.loadbalancer.server.port=3000"

networks:
  traefik-public:
    external: true