  version: '3.8'

  services:
    babapp-backend:
      restart: always
      build: .
      networks:
        - traefik-public
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.babapp-backend.tls=true"
        - "traefik.http.routers.babapp-backend.tls.certresolver=le"
        - "traefik.http.routers.babapp-backend.entrypoints=websecure"
        - "traefik.http.routers.babapp-backend.service=babapp-backend"
        - "traefik.http.routers.babapp-backend.rule=Host(`api.dashaljawhara.com`)"
        - "traefik.http.services.babapp-backend.loadbalancer.server.port=3366"

  networks:
    traefik-public:
      external: true